#!/usr/bin/sh
GROFF_NO_SGR=1 \
LESS_TERMCAP_md=$'\033[38;5;220m' \
LESS_TERMCAP_me=$'\033[0m' \
LESS_TERMCAP_us=$'\033[38;5;105m' \
LESS_TERMCAP_ue=$'\033[0m' \
LESS_TERMCAP_so=$'\033[48;2;47;47;89m\033[37m' \
LESS_TERMCAP_se=$'\033[0m' \
man "$@"
