#!/usr/bin/sh
# ozone platform is x11 and scaling is forced until electron compiles with the fixed chromium version
exec /usr/bin/teams-for-linux "$@" /usr/bin/teams-for-linux "$@" --enable-features=UseOzonePlatform --ozone-platform=x11 --force-device-scale-factor=1